---
name: test_package.yaml

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Poetry
        run: pip install poetry
      - name: Checkout code
        uses: actions/checkout@v5.0.0
      - name: Installing ccdcoe package
        continue-on-error: true
        run: pip install ccdcoe[cli_code] && ccdcoe --version
      - name: Clearing default .env
        run: sed -i -e 's/<<MANDATORY_VALUE>>/""/g' /home/runner/.ccdcoe/.env
      - name: Installing apt-get dependencies
        run: sudo apt-get update && sudo apt-get install -y python3-dev libldap2-dev libsasl2-dev libssl-dev
      - name: Install Dependencies
        run: poetry install --no-interaction --no-root && poetry install --only tests --no-interaction --no-root
      - name: Run Tests with Pytest
        run: poetry run tox
